[project]
name = "flight2d"
version = "0.1.0"
requires-python = ">=3.10"


[project.scripts]
flight2d = "flight2d.cli:main"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
where = ["src"]

